name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install deps
        run: npm ci

      - name: Build VuePress site
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        if: success()
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
          jekyll: false
          verbose: true
          fqdn: adocs.tianlab-tsinghua.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
